import { Avatar } from "./Avatar"
import { CharCounter } from "./CharCounter";
import { CommentModel, AuthorModel } from "../Interfaces"
import "./ReplyForm.css";

export const ReplyForm = ({authors, maxlength, updateBodyValue, addComment, comment}: {authors: AuthorModel[], maxlength: number, updateBodyValue?: any, addComment?: any, comment: CommentModel}) => {
  return(
    <>
    <div id="ReplyForm" className="replyformflex">
        <div className="replyformflex-first-row">
          {/* AVATAR OF ME*/}
          <Avatar author={authors.find((author) => author.id === 1)}/>
          {/* TEXT */}
          <textarea className="replyform-textarea"
            name="comment"
            value={comment.attributes.body}
            placeholder="Insert your comment..." 
            onChange={(event: React.ChangeEvent<HTMLTextAreaElement>) => {
            //check maxlength
            if (maxlength && event.target.value.length <= maxlength) {
                updateBodyValue(event.target.value);
            }
          }}
          />
          {/* CHAR COUNTER */}
          <CharCounter body={comment.attributes.body} maxlength={maxlength}/>
        </div>
        <div className="replyformflex-last-row">
          {/* CANCEL BUTTON */}
          <button 
          className="replyformflex-button-cancel"
          onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
              updateBodyValue("");
            }
          }>Cancel</button>

          {/* SAVE BUTTON */}
          <button 
          className="replyformflex-button-add"
          onClick={(event: React.MouseEvent<HTMLButtonElement>) => {
              if(comment.attributes.body.length>0){
                //console.log("Clicked ADD");
                //ADD an ID autogenerated
                comment.id=Math.floor(Math.random() * 1000);
                //console.log(comment);
                addComment(comment);
                updateBodyValue('');
              }
            }
          }>Add</button>
        </div>
    </div>
    </>
  )
}